# -*- coding: utf-8 -*-
"""Unemployment in India.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10rJINi9Y41HCLQmaeB8-YOWyaFr5txui
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/Unemployment in India.csv")

df.head()

df.tail()

df.shape

df.info()

df.describe()

x = df['Region']
x

y = df[' Estimated Unemployment Rate (%)']
y

df2=df.iloc[:,3]
df2

print(df.columns)

import plotly.express as px
import matplotlib.pyplot as plt

fg = px.bar(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment Rate(State wise) by Bar Graph',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.box (df,x='Region',y=' Estimated Unemployment Rate (%)', color='Region',
            title='Unemployment Rate (Statewise) by Box Plot',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.scatter(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
                title='Unemployment Rate (Statewise) by Scatter Plot',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.histogram(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
                title='Unemployment Rate (Statewise) by Histogram',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()